### ISSUE TITLE
Implementar autentificacion

### ISSUE THREAD

**Issue by agutierrezmorag** [agutierrezmorag/unap-chatbot#3]
## Descripción
Con la implementación de la pagina `📑 Documentos` se implemento la opción de subir y eliminar documentos con los cuales se contextualiza el modelo de chat para la generación de respuestas.  Los documentos con los que se interactúan son los presentes en el branch `test` de este repositorio.
Actualmente cualquier usuario puede subir y eliminar documentos.

## Objetivo
Implementar alguna forma de autentificación en la pagina `📑 Documentos` para restringir el acceso a personas selectas. Quizás sea necesario conversar con el profesor que tipo de autentificación seria necesaria. También habrá que informarle la manera con la que manejamos los documentos _(mediante este repo)_ y consultarle si esta bien o si sera necesario realizar cambios.

**Comment by agutierrezmorag** [comment]
El profesor menciono que una autentificación con correo y contraseña simple seria suficiente.

**Comment by agutierrezmorag** [comment]
También quizás sea lo mejor subir este apartado de administración de documentos como una app aparte (su propio repositorio y deploy).

**Comment by Gualterguaguita** [comment]
Ya se implemento el login a la pagina de documentos. En caso de ser necesario es posible alargar la duracion de la cookie.

**Comment by agutierrezmorag** [comment]
Ya integre lo que subiste con lo que hice en #6.
Lo de las cookies y vi que había una opción de registrar un usuario, habría que mencionarle ambas cosas al profe y ver que nos dice.

Si es que se puede, estaría bien cambiar los textos del cuadro de login a español
![imagen](https://github.com/agutierrezmorag/unap-chatbot/assets/84687977/03209426-24d2-4015-a65d-a007bc731b0c)

También me di cuenta que el código `st.warning("Por favor, ingrese sus credenciales.")` nunca se ejecuta, quizás habría que cambiar el `if` en el que esta o simplemente eliminar esa linea.

**Comment by agutierrezmorag** [comment]
En la ultima versión de `streamlit-authenticator` es posible definir manualmente los labels del formulario de inicio de sesión y ya fue implementado.
